# Generated by Django 4.1 on 2022-09-06 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_entregafinal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album_musica',
            old_name='estreno',
            new_name='lanzamiento',
        ),
        migrations.RenameField(
            model_name='videojuego',
            old_name='estreno',
            new_name='lanzamiento',
        ),
        migrations.AddField(
            model_name='album_musica',
            name='artista',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='album_musica',
            name='discografica',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='album_musica',
            name='genero',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='album_musica',
            name='nombre',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='director',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='genero',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='nombre',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='videojuego',
            name='compania',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='videojuego',
            name='genero',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='videojuego',
            name='nombre',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
