# Generated by Django 4.1 on 2022-09-07 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_entregafinal', '0002_rename_estreno_album_musica_lanzamiento_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videojuego',
            old_name='compania',
            new_name='compañia',
        ),
    ]
