# Generated by Django 4.1 on 2022-10-04 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_entregafinal', '0005_pelicula_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='usuarioid',
            field=models.IntegerField(null=True),
        ),
    ]
