# Generated by Django 4.1 on 2022-10-04 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_entregafinal', '0006_pelicula_usuarioid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pelicula',
            name='usuario',
        ),
    ]
