# Generated by Django 4.1 on 2022-10-04 20:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_entregafinal', '0007_remove_pelicula_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='usuarioid',
            field=models.ForeignKey(null='True', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
