# Generated by Django 4.1 on 2022-10-04 23:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_entregafinal', '0010_pelicula_descripcion_alter_pelicula_usuarioid'),
    ]

    operations = [
        migrations.AddField(
            model_name='videojuego',
            name='descripcion',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='videojuego',
            name='portada',
            field=models.ImageField(blank=True, null=True, upload_to='portadas'),
        ),
        migrations.AddField(
            model_name='videojuego',
            name='usuarioid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
